apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: f6v3ku16b-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/f6v3ku16b-dotnet-basic-gitops