apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: f6v3ku16b-dotnet-basic
  janus-idp.io/tekton: f6v3ku16b-dotnet-basic
  backstage.io/kubernetes-id: f6v3ku16b-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: f6v3ku16b-dotnet-basic
resources:
- deployment.yaml
- route.yaml
- service.yaml
